version: '3.9'

services:
  node-rabbitmq-mongodb-prod:
    container_name: node-rabbitmq-mongodb-prod
    build:
      context: .
    restart: always
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4001:4001
    command: 'npm run start:prod'
    environment:
      NODE_ENV: production
      PORT: 4001
      DATABASE_URL: mongodb://mongo_db:27018/test_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:6.0
    container_name: mongo_db
    command: mongod --port 27018
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - 27018:27018
    networks:
      - proxynet

volumes:
  mongo_db:

networks:
  proxynet:
    name: custom_network
    driver: bridge
